vich_uploader:
    db_driver: orm
    metadata:
        type: annotation

    mappings:
        picture_profile:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
